apiVersion: v1
kind: Template
metadata:
  name: couchbase-petset-persistent
  annotations:
    description: >-
      Couchbase database service, with persistent storage.
      You must have persistent volumes available
      in your cluster to use this template.
    iconClass: icon-couchbase
    tags: 'database,couchbase'
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: '${DATABASE_SERVICE_NAME}'
    spec:
      ports:
        - name: couchbase
          port: 8091
      selector:
        name: '${DATABASE_SERVICE_NAME}'
  - kind: Service
    apiVersion: v1
    metadata:
      name: '${DATABASE_SERVICE_NAME}-data'
      annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    spec:
      clusterIP: None
      ports:
        - name: couchbase
          port: 8091
      selector:
        name: '${DATABASE_SERVICE_NAME}'
        type: data
  - apiVersion: apps/v1alpha1
    kind: PetSet
    metadata:
      name: ${DATABASE_SERVICE_NAME}-data
    spec:
      serviceName: ${DATABASE_SERVICE_NAME}-data
      replicas: 2
      template:
        metadata:
          labels:
            name: ${DATABASE_SERVICE_NAME}-data
            app: couchbase
            type: data
          annotations:
            pod.alpha.kubernetes.io/initialized: "true"
        spec:
          terminationGracePeriodSeconds: 86400
          containers:
          - name: couchbase
            image: 172.30.25.189:5000/openshift/couchbase@sha256:39acd1ae66dc640dd72111882dc6b71697942f6961c1bc97f550ce22ab2c0ca3
            imagePullPolicy: IfNotPresent
            readinessProbe:
              initialDelaySeconds: 30
              tcpSocket:
                port: 8091
              timeoutSeconds: 1
            livenessProbe:
              initialDelaySeconds: 30
              tcpSocket:
                port: 8091
              timeoutSeconds: 1
            env:
            - name: COUCHBASE_USER
              value: ${COUCHBASE_USER}
            - name: COUCHBASE_PASSWORD
              value: ${COUCHBASE_PASSWORD}
            - name: COUCHBASE_DATABASE
              value: ${COUCHBASE_DATABASE}
            - name: COUCHBASE_DATABASE
              value: ${COUCHBASE_DATABASE}
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Mi
            ports:
            - containerPort: 8091
              name: couchbase
            resources:
              requests:
                memory: ${MEMORY_LIMIT}
                cpu: 0.25
              limits:
                memory: ${MEMORY_LIMIT}
            volumeMounts:
            - mountPath: /opt/couchbase/var
              name: data
          - name: couchbase-sidecar
            image: jetstackexperimental/couchbase-sidecar
            imagePullPolicy: Always
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            ports:
            - containerPort: 8080
              name: sidecar
      volumeClaimTemplates:
      - metadata:
          name: data
          annotations:
            volume.alpha.kubernetes.io/storage-class: '${STORAGE_CLASS}'
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: '${VOLUME_CAPACITY}'
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${DATABASE_SERVICE_NAME}-query
    spec:
      replicas: 1
      selector:
        name: ${DATABASE_SERVICE_NAME}
      template:
        metadata:
          labels:
            name: ${DATABASE_SERVICE_NAME}
            app: couchbase
            type: query
        spec:
          containers:
          - env:
            - name: COUCHBASE_USER
              value: ${COUCHBASE_USER}
            - name: COUCHBASE_PASSWORD
              value: ${COUCHBASE_PASSWORD}
            - name: COUCHBASE_DATABASE
              value: ${COUCHBASE_DATABASE}
            - name: COUCHBASE_DATABASE
              value: ${COUCHBASE_DATABASE}
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Mi
            image: ' '
            imagePullPolicy: IfNotPresent
            readinessProbe:
              initialDelaySeconds: 30
              tcpSocket:
                port: 8091
              timeoutSeconds: 1
            livenessProbe:
              initialDelaySeconds: 30
              tcpSocket:
                port: 8091
              timeoutSeconds: 1
            name: couchbase
            ports:
            - containerPort: 8091
              name: couchbase
            resources:
              requests:
                memory: ${MEMORY_LIMIT}
                cpu: 0.25
              limits:
                memory: ${MEMORY_LIMIT}
            volumeMounts:
            - mountPath: /opt/couchbase/var
              name: ${DATABASE_SERVICE_NAME}-data
          volumes:
          - name: ${DATABASE_SERVICE_NAME}-data
            emptyDir: {}
      triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
          - couchbase
          from:
            kind: ImageStreamTag
            name: couchbase:4.5.1-enterprise
            namespace: ${NAMESPACE}
        type: ImageChange
      - type: ConfigChange
parameters:
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    value: 1Gi
    required: true
  - name: NAMESPACE
    displayName: Namespace
    description: The OpenShift Namespace where the ImageStream resides.
    value: openshift
  - name: DATABASE_SERVICE_NAME
    displayName: Database Service Name
    description: The name of the OpenShift Service exposed for the database.
    value: couchbase
    required: true
  - name: COUCHBASE_USER
    displayName: Couchbase Connection Username
    description: Username for Couchbase user that will be used for accessing the database.
    generate: expression
    from: 'user[A-Z0-9]{3}'
    required: true
  - name: COUCHBASE_PASSWORD
    displayName: Couchbase Connection Password
    description: Password for the Couchbase connection user.
    generate: expression
    from: '[a-zA-Z0-9]{16}'
    required: true
  - name: COUCHBASE_DATABASE
    displayName: Couchbase Database Name
    description: Name of the Couchbase database accessed.
    value: sampledb
    required: true
  - name: VOLUME_CAPACITY
    displayName: Volume Capacity
    description: 'Volume space available for data, e.g. 512Mi, 2Gi.'
    value: 1Gi
    required: true
  - name: STORAGE_CLASS
    displayName: Storage Class
    description: 'Storage Class of the volume space for data, e.g. gp2, st1'
    value: gp2
    required: true
labels:
  template: couchbase-peset-persistent-template

